void sendEVSEdata();
bool queryEVSE();
String printIP(IPAddress);
void parseBytes(const char*, char, byte*, int, int);
void ICACHE_RAM_ATTR handleMeterInt();
void updateMeterData();
int getChargingTime();
void rfidloop();
void pushWebsocketEVSEData();
void sendStatus();
void printScanResult(int);
void logLatest(String, String);
void updateLog(bool);
bool queryEVSE();
bool activateEVSE();
bool deactivateEVSE(bool);
bool setEVSEcurrent();
void pushSessionTimeOut();
void sendEVSEdata();
void sendTime();
void sendUserList(int, AsyncWebSocketClient *);
void onWsEvent(AsyncWebSocket*, AsyncWebSocketClient*, AwsEventType, void*, uint8_t*, size_t);
void ShowReaderDetails();
void setupRFID(int, int);
bool connectSTA(const char*, const char* , byte[]);
bool startAP(const char*, const char*);
bool loadConfiguration();
void fallbacktoAPMode();
void startWebserver();
void setWebEvents();
